version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./app-config:/app/app-config
    expose:
      - 8000
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
